import { ReactionMap } from '../types';

export const reactions: ReactionMap = {
  // Water reactions
  water_fire: { result: 'steam', count: 15 },
  water_oil: { result: 'slick', count: 8 },
  water_acid: { result: 'toxicfumes', count: 12 },
  water_lava: { result: 'obsidian', count: 1 },
  water_smoke: { result: 'soot', count: 10 },
  water_gas: { result: 'bubbles', count: 10 },
  water_sand: { result: 'mud', count: 8 },
  water_metal: { result: 'rust', count: 5 },
  water_wood: { result: 'moss', count: 6 },
  water_chemical: { result: 'acidwater', count: 10 },
  water_glass: { result: 'lens', count: 1 },
  water_ice: { result: 'iceblock', count: 1 },
  water_plasma: { result: 'explosion', count: 20 },
  water_napalm: { result: 'floatingfire', count: 10 },
  // Fire reactions
  fire_oil: { result: 'largefire', count: 15 },
  fire_acid: { result: 'acidfumes', count: 12 },
  fire_lava: { result: 'magma', count: 8 },
  fire_smoke: { result: 'smog', count: 12 },
  fire_gas: { result: 'explosion', count: 20 },
  fire_sand: { result: 'glasspane', count: 1 },
  fire_metal: { result: 'moltenmetal', count: 6 },
  fire_wood: { result: 'ash', count: 10 },
  fire_chemical: { result: 'plasmafire', count: 8 },
  fire_glass: { result: 'moltenglass', count: 6 },
  fire_ice: { result: 'water', count: 10 },
  fire_plasma: { result: 'supernova', count: 15 },
  fire_napalm: { result: 'inferno', count: 15 },
  // Oil reactions
  oil_acid: { result: 'toxicsludge', count: 8 },
  oil_lava: { result: 'inferno', count: 15 },
  oil_smoke: { result: 'tar', count: 8 },
  oil_gas: { result: 'fuel', count: 10 },
  oil_sand: { result: 'tarsand', count: 6 },
  oil_metal: { result: 'lubricant', count: 6 },
  oil_wood: { result: 'preservedwood', count: 6 },
  oil_chemical: { result: 'plastic', count: 6 },
  oil_glass: { result: 'smudge', count: 4 },
  oil_ice: { result: 'frozenoil', count: 6 },
  oil_plasma: { result: 'explosion', count: 20 },
  oil_napalm: { result: 'napalm', count: 10 },
  // Acid reactions
  acid_lava: { result: 'obsidian', count: 1 },
  acid_smoke: { result: 'chokinghazard', count: 10 },
  acid_gas: { result: 'mustardgas', count: 12 },
  acid_sand: { result: 'dissolvedsand', count: 6 },
  acid_metal: { result: 'hydrogengas', count: 8 },
  acid_wood: { result: 'rot', count: 8 },
  acid_chemical: { result: 'explosion', count: 20 },
  acid_glass: { result: 'etchedglass', count: 4 },
  acid_ice: { result: 'acidwater', count: 10 },
  acid_plasma: { result: 'radioactiveslop', count: 12 },
  acid_napalm: { result: 'corrosivefire', count: 10 },
  // Lava reactions
  lava_smoke: { result: 'ashcloud', count: 12 },
  lava_gas: { result: 'explosion', count: 20 },
  lava_sand: { result: 'glasspane', count: 1 },
  lava_metal: { result: 'moltenmetal', count: 8 },
  lava_wood: { result: 'charcoal', count: 8 },
  lava_chemical: { result: 'explosion', count: 20 },
  lava_glass: { result: 'moltenglass', count: 6 },
  lava_ice: { result: 'obsidian', count: 1 },
  lava_plasma: { result: 'magmacore', count: 8 },
  lava_napalm: { result: 'inferno', count: 15 },
  // Smoke reactions
  smoke_gas: { result: 'smog', count: 12 },
  smoke_sand: { result: 'duststorm', count: 10 },
  smoke_metal: { result: 'soot', count: 6 },
  smoke_wood: { result: 'charredwood', count: 6 },
  smoke_chemical: { result: 'nervegas', count: 12 },
  smoke_glass: { result: 'smokedglass', count: 4 },
  smoke_ice: { result: 'frostymist', count: 10 },
  smoke_plasma: { result: 'aurora', count: 8 },
  smoke_napalm: { result: 'thicksmoke', count: 12 },
  // Gas reactions
  gas_sand: { result: 'quicksand', count: 8 },
  gas_metal: { result: 'rust', count: 6 },
  gas_wood: { result: 'vaportrail', count: 8 },
  gas_chemical: { result: 'toxicfumes', count: 12 },
  gas_glass: { result: 'condensation', count: 6 },
  gas_ice: { result: 'dryice', count: 6 },
  gas_plasma: { result: 'explosion', count: 20 },
  gas_napalm: { result: 'fuelairblast', count: 15 },
  // Sand reactions
  sand_metal: { result: 'alloy', count: 6 },
  sand_wood: { result: 'soil', count: 6 },
  sand_chemical: { result: 'acidwater', count: 8 },
  sand_glass: { result: 'glasspane', count: 1 },
  sand_ice: { result: 'permafrost', count: 6 },
  sand_plasma: { result: 'fulgurite', count: 6 },
  sand_napalm: { result: 'stickysand', count: 8 },
  // Metal reactions
  metal_wood: { result: 'reinforcedwood', count: 6 },
  metal_chemical: { result: 'battery', count: 6 },
  metal_glass: { result: 'mirror', count: 1 },
  metal_ice: { result: 'coldmetal', count: 6 },
  metal_plasma: { result: 'railguncore', count: 6 },
  metal_napalm: { result: 'heatedmetal', count: 6 },
  // Wood reactions
  wood_chemical: { result: 'rot', count: 8 },
  wood_glass: { result: 'framedglass', count: 1 },
  wood_ice: { result: 'frozenwood', count: 6 },
  wood_plasma: { result: 'ash', count: 10 },
  wood_napalm: { result: 'inferno', count: 15 },
  // Chemical reactions
  chemical_glass: { result: 'beaker', count: 1 },
  chemical_ice: { result: 'slush', count: 8 },
  chemical_plasma: { result: 'radioactiveslop', count: 12 },
  chemical_napalm: { result: 'explosion', count: 20 },
  // Glass reactions
  glass_ice: { result: 'brittle', count: 6 },
  glass_plasma: { result: 'neonlight', count: 8 },
  glass_napalm: { result: 'smokedglass', count: 4 },
  // Ice reactions
  ice_plasma: { result: 'steamcloud', count: 15 },
  ice_napalm: { result: 'water', count: 10 },
  // Plasma reactions
  plasma_napalm: { result: 'supernova', count: 15 },
};

export const getReaction = (a: string, b: string) => {
  const key = `${a}_${b}`;
  const rev = `${b}_${a}`;
  return reactions[key] || reactions[rev];
};